name: setup postgres
description: Setup and start a postgres database

runs:
  using: composite
  steps:
    - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Setup postgres
      uses: docker://postgis/postgis:15-3.4-alpine
      with:
        env: |
          POSTGRES_USER=postgres
          POSTGRES_PASSWORD=postgres
          POSTGRES_DB=postgres
        ports: 5432:5432
        healthcheck: |
          CMD pg_isready -U postgres
        entrypoint: |
          bash -c '
            echo "host all all all trust" >> /var/lib/postgresql/data/pg_hba.conf
            echo "listen_addresses = '*'" >> /var/lib/postgresql/data/postgresql.conf
            /docker-entrypoint.sh postgres &
            until pg_isready -U postgres; do
              sleep 1
            done
            psql -U postgres -c "CREATE DATABASE postgres;"
            psql -U postgres -c "CREATE USER postgres WITH SUPERUSER PASSWORD '"'"'postgres'"'"';"
            psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE postgres TO postgres;"
            psql -U postgres -c "ALTER USER postgres WITH PASSWORD '"'"'postgres'"'"';"
            psql -U postgres -c "ALTER USER postgres WITH LOGIN;"
            psql -U postgres -c "ALTER USER postgres WITH CREATEDB;"
            psql -U postgres -c "ALTER USER postgres WITH CREATEROLE;"
            psql -U postgres -c "ALTER USER postgres WITH REPLICATION;"
            psql -U postgres -c "ALTER USER postgres WITH BYPASSRLS;"
            psql -U postgres -c "ALTER USER postgres WITH CONNECTION LIMIT -1;"
            psql -U postgres -c "ALTER USER postgres WITH VALID UNTIL '"'"'infinity'"'"';"
            psql -U postgres -c "ALTER USER postgres WITH INHERIT 
            '