name: setup directus
description: Setup and start a directus instance

runs:
  using: composite
  steps:
    - name: Setup postgres
      uses: ./.github/utils/setup-postgres
      with:
        user: postgres
        password: postgres
        database: postgres
        port: 8055
    - name: Setup directus
      uses: docker://directus/directus:10.7.2
      with:
        env: |
          DB_CLIENT=pg
          DB_HOST=postgres
          DB_PORT=postgres
          DB_USER=postgres
          DB_PASSWORD=postgres
          DB_DATABASE=postgres
          LOG_LEVEL=debug
          KEY="0fda9121-269d-44bd-91f2-4ff05be14b4b
          SECRET="86cb4a76-a4c6-4ce7-8181-b0445d95675c"
          CACHE_ENABLED=false